### ISSUE TITLE
Linux:arm64/V8 Version of e3dc-to-mqtt

### ISSUE THREAD

**Issue by devganny** [mdhom/e3dc-to-mqtt#8]
Hi Max, very good wrapper works like a charm on x86 Portainer. It would be great to use it in docker on raspberry pi. Would it be possible for you to compile it also for Linux:arm64/V8 ? That would be fantastic.
Thanks very much in advance.
Best regards

**Comment by Dirnei** [comment]
hi @devganny 
is the linux/arm/v7 image not working for you? i'm running it on my rasperrby :)

If not I can have a look how to compile it 👍

**Comment by devganny** [comment]
I tried to run it in Docker on a raspi4 but it did not work. I try to install it on a home assitant system. Absolutly great would be a home assistant integration. But I do not know how to build a integration. I only know, that they are based on docker technology.
https://developers.home-assistant.io/docs/creating_component_index/

**Comment by Dirnei** [comment]
Here is my `docker-compose.yml`

```yaml
version: '3.3'

services:
  e3dc-to-mqtt:
    image: "mdhom/e3dc-to-mqtt:latest"
    restart: always
    environment:
      - MQTT_BROKER=127.0.0.1
      - E3DC_HOST=192.168.0.5
      - E3DC_USERNAME=your@email.com
      - E3DC_PASSWORD=password
      - E3DC_RSCPKEY=SETONYOURDEVICE
```

Simply put in somewhere on the raspi and then start it with: `docker compose up -d`
It's working fine on my raspi4 🤔 

> To stop it run `docker compose down` in the same directory
